source 'https://rubygems.org'

gem 'telegram_bot', '0.0.8'
gem 'telegram-bot-ruby'
gem 'nokogiri'
gem 'twilio-ruby'
gem 'rss'
gem 'httparty'
gem 'nokogiri'
gem 'uri'
gem 'goodreads'
gem 'openlibrary'
gem 'google-api-client', '~> 0.39'
gem 'googleauth'
gem 'dotenv'
gem 'rest-client'
gem 'sinatra'
gem 'twitter'
gem 'typhoeus'
gem 'oauth'
gem 'gemini-ai'
gem 'sendgrid-ruby'
gem 'openstreetmap'
gem 'rmagick'
gem 'whatsapp_bot'
gem 'selenium-webdriver'